
// Generated by Cadence Genus(TM) Synthesis Solution 21.17-s066_1
// Generated on: Jul 28 2023 09:12:34 CEST (Jul 28 2023 07:12:34 UTC)

// Verification Directory fv/compGRNG 

module compGRNG(clk, LD_seed, result);
  input clk, LD_seed;
  output [7:0] result;
  wire clk, LD_seed;
  wire [7:0] result;
  wire [6:0] unfilteredLFSR1;
  wire [9:0] unfilteredLFSR0;
  wire [9:0] unfilteredLFSR5;
  wire [7:0] unfilteredLFSR3;
  wire [8:0] unfilteredLFSR2;
  wire [8:0] unfilteredLFSR6;
  wire [8:1] LFSR7_r_LFSR;
  wire [6:0] unfilteredLFSR4;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, UNCONNECTED42,
       UNCONNECTED43, UNCONNECTED44, UNCONNECTED45, UNCONNECTED46;
  wire UNCONNECTED47, UNCONNECTED48, UNCONNECTED49, UNCONNECTED50,
       UNCONNECTED51, UNCONNECTED52, UNCONNECTED53, UNCONNECTED54;
  wire UNCONNECTED55, UNCONNECTED56, UNCONNECTED57, UNCONNECTED58,
       UNCONNECTED59, UNCONNECTED60, UNCONNECTED61, UNCONNECTED62;
  wire UNCONNECTED63, UNCONNECTED64, UNCONNECTED65, UNCONNECTED66, n_0,
       n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_196, n_197, n_198, n_199, n_200, n_201, n_202, n_203;
  wire n_204, n_205, n_206, n_207, n_208, n_211, n_212, n_213;
  wire n_214, n_215, n_216, n_217, n_218, n_219, n_220, n_221;
  wire n_223, n_224, n_225, n_226, n_227, n_228, n_229, n_230;
  wire n_231, n_232, n_233, n_234, n_235, n_236, n_237, n_238;
  wire n_239, n_240, n_241, n_242, n_243, n_244, n_245, n_246;
  wire n_247, n_248, n_249, n_250, n_251, n_252, n_253, n_254;
  wire n_255, n_256, n_257, n_258, n_259, n_260, n_261, n_262;
  wire n_263, n_264, n_265, n_266, n_267, n_268, n_269, n_270;
  wire n_271, n_272, n_273, n_274, n_275, n_276, n_277, n_278;
  wire n_279, n_280, n_281, n_283, n_284, n_285, n_286, n_287;
  wire n_288, n_289, n_290, n_291, n_292, n_293, n_294, n_295;
  wire n_296, n_297, n_298, n_299, n_300, n_301, n_302, n_303;
  wire n_304, n_305, n_306, n_307, n_308, n_309, n_310, n_311;
  wire n_312, n_313, n_314, n_315, n_316, n_317, n_318, n_319;
  wire n_320, n_321, n_322, n_323, n_324, n_325, n_326, n_327;
  wire n_328, n_329, n_330, n_331, n_332, n_333, n_334, n_335;
  wire n_336, n_337, n_338, n_339, n_340, n_341, n_342, n_343;
  wire n_344, n_345, n_346, n_347, n_348, n_349, n_350, n_351;
  wire n_352, n_353, n_356;
  wire w, w0;
  nand g8670__2398 (result[1], w, w0, n_356);
  or g0 (w0, n_267, n_320);
  or g (w, n_349, n_285);
  wire w1, w2;
  nor g8672__5107 (n_356, w1, n_353, w2);
  and g2 (w2, n_325, n_289);
  and g1 (w1, n_323, n_291);
  wire w3;
  nand g8671__6260 (result[2], n_348, n_352, w3);
  or g3 (w3, n_264, result[3]);
  wire w4;
  nand g8674__4319 (n_353, n_346, n_350, w4);
  or g4 (w4, n_342, n_302);
  wire w5;
  nor g8673__8428 (n_352, n_351, n_321, w5);
  and g5 (w5, n_249, n_296);
  nand g8676__5526 (n_351, n_243, n_294, n_335, n_347);
  wire w6, w7;
  nor g8675__6783 (n_350, w6, n_345, w7);
  and g7 (w7, n_271, n_338);
  and g6 (w6, n_349, n_212);
  wire w8, w9;
  nor g8679__3680 (n_348, w8, n_341, w9);
  and g9 (w9, n_206, n_333);
  and g8 (w8, n_343, n_331);
  not g8680 (n_347, n_344);
  wire w10;
  nor g8677__1617 (n_346, n_340, n_324, w10);
  and g10 (w10, unfilteredLFSR1[0], n_202);
  wire w11;
  nand g8678__2802 (n_345, n_334, n_339, w11);
  or g11 (w11, n_295, n_286);
  wire w12, w13;
  nand g8682__1705 (n_344, w12, w13, n_337);
  or g13 (w13, n_342, n_300);
  or g12 (w12, n_343, n_312);
  wire w14, w15;
  nand g8683__5122 (n_341, w14, w15, n_336);
  or g15 (w15, n_298, n_234);
  or g14 (w14, n_299, n_322);
  nand g8681__8246 (n_340, n_199, n_297, n_332, n_317);
  wire w16, w17;
  nor g8684__7098 (n_339, w16, n_328, w17);
  and g17 (w17, n_232, n_283);
  and g16 (w16, n_254, n_338);
  wire w18, w19;
  nor g8687__6131 (n_337, w18, n_330, w19);
  and g19 (w19, n_186, n_308);
  and g18 (w18, n_318, n_309);
  wire w20, w21;
  nor g8688__1881 (n_336, w20, n_319, w21);
  and g21 (w21, n_185, n_315);
  and g20 (w20, n_329, n_225);
  wire w22, w23;
  and g8689__5115 (n_335, w22, w23);
  nand g23 (w23, n_239, n_306);
  nand g22 (w22, n_305, n_314);
  wire w24;
  nor g8686__7482 (n_334, w24, n_326);
  and g24 (w24, n_333, n_104);
  wire w25;
  nand g8690__4733 (n_332, w25, n_327);
  or g25 (w25, n_331, n_293);
  wire w26, w27;
  nand g8693__6161 (n_330, w26, w27, n_208);
  or g27 (w27, n_177, n_311);
  or g26 (w26, n_329, n_290);
  wire w28, w29;
  nand g8685__9315 (n_328, w28, w29);
  or g29 (w29, n_327, n_313);
  or g28 (w28, n_316, n_310);
  nor g8691__9945 (n_326, n_325, n_307);
  wire w30;
  nor g8692__2883 (n_324, w30, n_323);
  and g30 (w30, n_322, n_287);
  wire w31, w32;
  nand g8695__2346 (n_321, w31, w32, n_301);
  or g32 (w32, n_303, n_320);
  or g31 (w31, n_169, n_260);
  wire w33, w34;
  nand g8696__1666 (n_319, w33, w34);
  or g34 (w34, n_318, n_221);
  or g33 (w33, n_176, n_292);
  wire w35;
  nand g8694__7410 (n_317, w35, n_316);
  or g35 (w35, n_288, n_315);
  not g8697 (n_314, n_304);
  and g8700__6417 (n_313, n_311, n_312);
  nor g8699__5477 (n_310, n_308, n_309);
  nor g8698__2398 (n_307, n_305, n_306);
  wire w36;
  nor g8701__5107 (n_304, w36, n_251);
  and g36 (w36, n_338, n_303);
  wire w37;
  nor g8702__6260 (n_302, w37, n_323);
  and g37 (w37, n_338, n_102);
  wire w38;
  nor g8703__4319 (n_301, w38, n_240);
  and g38 (w38, n_338, n_255);
  wire w39;
  nor g8705__8428 (n_300, w39, n_299);
  and g39 (w39, n_338, n_298);
  wire w40, w41;
  and g8706__5526 (n_297, w40, w41);
  nand g41 (w41, n_295, n_296);
  nand g40 (w40, n_265, n_338);
  wire w42, w43;
  and g8707__6783 (n_294, w42, w43);
  nand g43 (w43, n_252, n_203);
  nand g42 (w42, n_250, n_338);
  not g8708 (n_293, n_292);
  not g8713 (n_291, n_290);
  wire w44;
  nand g8704__3680 (n_289, w44, n_274);
  or g44 (w44, n_320, result[3]);
  nand g8712__1617 (n_292, n_288, n_338);
  nand g8714__2802 (n_322, n_219, n_338);
  nand g8716__1705 (n_290, n_308, n_338);
  nor g8709__5122 (n_309, n_311, result[3]);
  nor g8710__8246 (n_333, n_231, result[3]);
  or g8711__7098 (n_312, n_281, result[3]);
  nor g8715__6131 (n_306, n_237, result[3]);
  nor g8717__1881 (n_315, n_287, result[3]);
  not g8718 (n_338, result[3]);
  wire w45, w46;
  nand g8719__5115 (result[3], w45, w46, n_284);
  or g46 (w46, n_277, n_285);
  or g45 (w45, n_148, n_286);
  wire w47, w48;
  nor g8721__7482 (n_284, w47, n_280, w48);
  and g48 (w48, n_273, n_283);
  and g47 (w47, n_145, n_305);
  wire w49, w50;
  nand g8720__4733 (result[0], w49, w50, n_279);
  or g50 (w50, unfilteredLFSR0[0], n_281);
  or g49 (w49, n_244, n_287);
  nand g8723__6161 (n_280, n_207, n_266, n_278);
  wire w51, w52;
  nor g8722__9315 (n_279, w51, n_276, w52);
  and g52 (w52, n_256, n_288);
  and g51 (w51, n_258, n_236);
  wire w53, w54;
  nor g8725__9945 (n_278, w53, n_275, w54);
  and g54 (w54, n_146, n_223);
  and g53 (w53, n_277, n_296);
  nand g8724__2883 (n_276, n_246, n_269, n_272);
  wire w55;
  nand g8726__2346 (n_275, w55, n_270);
  or g55 (w55, n_273, n_274);
  wire w56;
  nor g8728__1666 (n_272, n_257, n_259, w56);
  and g56 (w56, n_261, n_238);
  not g8730 (n_271, n_268);
  nor g8727__7410 (n_270, n_217, n_331, n_248);
  wire w57;
  nor g8729__6417 (n_269, w57, n_262);
  and g57 (w57, n_228, unfilteredLFSR0[0]);
  wire w58, w59;
  and g8731__5477 (n_268, w58, w59);
  nand g59 (w59, n_349, n_233);
  nand g58 (w58, n_267, n_305);
  wire w60, w61, w62;
  and g8732__2398 (n_266, w60, w61, w62);
  nand g62 (w62, n_216, n_229);
  nand g61 (w61, n_247, n_308);
  nand g60 (w60, n_215, n_230);
  not g8738 (n_265, n_263);
  not g8739 (n_264, n_253);
  wire w63, w64;
  and g8742__5107 (n_263, w63, w64);
  nand g64 (w64, n_295, n_226);
  nand g63 (w63, n_349, n_296);
  wire w65;
  nor g8735__6260 (n_262, w65, n_261);
  and g65 (w65, n_274, n_260);
  wire w66;
  nor g8734__4319 (n_259, w66, n_258);
  and g66 (w66, n_342, n_285);
  wire w67, w68;
  nand g8733__8428 (n_257, w67, w68);
  or g68 (w68, n_245, n_320);
  or g67 (w67, n_256, n_311);
  wire w69, w70;
  nand g8737__5526 (n_255, w69, w70);
  or g70 (w70, n_242, n_260);
  or g69 (w69, n_241, n_274);
  wire w71, w72;
  nand g8744__6783 (n_254, w71, w72);
  or g72 (w72, n_295, n_285);
  or g71 (w71, n_93, n_286);
  wire w73, w74;
  nand g8743__3680 (n_253, w73, w74);
  or g74 (w74, n_251, n_320);
  or g73 (w73, n_252, n_235);
  wire w75, w76;
  nand g8740__1617 (n_250, w75, w76);
  or g76 (w76, n_249, n_285);
  or g75 (w75, n_168, n_286);
  wire w77, w78;
  nand g8745__2802 (n_248, w77, w78);
  or g78 (w78, n_147, n_260);
  or g77 (w77, n_247, n_287);
  wire w79, w80;
  and g8736__1705 (n_246, w79, w80);
  nand g80 (w80, n_244, n_308);
  nand g79 (w79, n_245, n_305);
  wire w81, w82;
  and g8741__5122 (n_243, w81, w82);
  nand g82 (w82, n_241, n_283);
  nand g81 (w81, n_242, n_224);
  nor g8746__8246 (n_240, n_239, n_274);
  nand g8749__7098 (n_238, n_237, n_286);
  nand g8748__6131 (n_236, n_234, n_235);
  nor g8750__1881 (n_233, n_232, n_274);
  nor g8747__5115 (n_331, n_141, n_231);
  not g8752 (n_230, n_342);
  not g8753 (n_229, n_311);
  not g8760 (n_296, n_235);
  not g8751 (n_231, n_228);
  nand g8755__7482 (n_342, n_308, n_227);
  nand g8756__4733 (n_311, n_204, n_227);
  nand g8764__6161 (n_235, n_226, n_227);
  not g8758 (n_287, n_225);
  not g8759 (n_286, n_224);
  nand g8757__9315 (n_274, n_223, n_227);
  nor g8754__9945 (n_228, n_211, result[4]);
  nor g8761__2883 (n_225, n_234, result[4]);
  nor g8763__2346 (n_224, n_285, result[4]);
  nor g8762__1666 (n_305, n_237, result[4]);
  not g8765 (n_227, result[4]);
  nand g8766__7410 (result[4], n_221, n_220);
  wire w83, w84;
  nor g8767__6417 (n_220, w83, n_218, w84);
  and g84 (w84, n_98, n_219);
  and g83 (w83, n_200, n_226);
  wire w85;
  nand g8768__5477 (n_218, n_281, n_214, w85);
  or g85 (w85, n_213, n_320);
  wire w86, w87;
  nand g8769__2398 (n_217, w86, w87);
  or g87 (w87, n_215, n_234);
  or g86 (w86, n_216, n_221);
  wire w88, w89;
  nor g8770__5107 (n_214, w88, n_201, w89);
  and g89 (w89, n_97, n_308);
  and g88 (w88, n_213, n_283);
  not g8771 (n_221, n_288);
  nor g8773__6260 (n_212, n_232, n_260);
  nor g8772__4319 (n_288, n_189, n_211);
  not g8776 (n_237, n_283);
  not g8777 (n_260, n_226);
  nor g8778__8428 (n_283, n_285, result[5]);
  nor g8775__5526 (n_308, n_170, result[5]);
  or g8774__6783 (n_211, n_190, result[6], result[5]);
  nor g8779__3680 (n_226, n_320, result[5]);
  nand g8780__1617 (result[5], n_234, n_205);
  or g8781__2802 (n_208, n_206, n_207);
  wire w90, w91;
  nor g8782__1705 (n_205, w90, n_204, w91);
  and g91 (w91, n_173, n_223);
  and g90 (w90, n_172, n_203);
  DFF_X2 \LFSR0_r_LFSR_reg[1] (.CK (clk), .D (n_198), .Q (UNCONNECTED),
       .QN (unfilteredLFSR0[0]));
  not g8785 (n_207, n_202);
  nor g8790__5122 (n_201, n_200, n_285);
  nand g8786__8246 (n_199, n_349, n_219);
  wire w92;
  nor g8788__7098 (n_202, w92, n_281);
  and g92 (w92, n_140, n_139);
  wire w93;
  nor g8787__6131 (n_256, w93, n_187);
  and g93 (w93, n_180, n_195);
  nand g8791__1881 (n_198, n_193, n_188);
  wire w94;
  nand g8796__5115 (n_245, w94, n_197);
  or g94 (w94, n_196, n_56);
  wire w95;
  nand g8797__7482 (n_261, w95, n_197);
  or g95 (w95, n_191, n_196);
  DFF_X2 \LFSR5_r_LFSR_reg[1] (.CK (clk), .D (n_194), .Q
       (UNCONNECTED0), .QN (unfilteredLFSR5[0]));
  wire w96;
  nor g8795__4733 (n_258, w96, n_192);
  and g96 (w96, n_162, n_195);
  not g8793 (n_234, n_219);
  DFF_X2 \LFSR3_r_LFSR_reg[1] (.CK (clk), .D (n_181), .Q
       (UNCONNECTED1), .QN (unfilteredLFSR3[0]));
  not g8804 (n_285, n_203);
  nand g8789__6161 (n_194, n_193, n_171);
  not g8803 (n_197, n_192);
  wire w97;
  nand g8794__9315 (n_244, w97, unfilteredLFSR0[9]);
  or g97 (w97, n_191, n_179);
  nor g8798__9945 (n_219, n_190, n_161, result[6]);
  nand g8792__2883 (n_281, n_189, n_204);
  wire w98, w99, w100, w101;
  nand g8805__2346 (n_188, w99, w101);
  nand g101 (w101, w100, unfilteredLFSR0[6]);
  not g100 (w100, n_187);
  nand g99 (w99, w98, n_187);
  not g98 (w98, unfilteredLFSR0[6]);
  not g8821 (n_186, n_185);
  wire w102;
  nand g8816__1666 (n_303, n_183, n_184, w102);
  or g102 (w102, n_182, n_178);
  wire w103;
  nand g8823__7410 (n_251, n_183, n_184, w103);
  or g103 (w103, n_182, n_37);
  nor g8809__6417 (n_203, result[7], result[6]);
  nand g8814__5477 (n_181, n_193, n_154);
  wire w104;
  nor g8806__2398 (n_180, w104, n_179);
  and g104 (w104, n_17, unfilteredLFSR0[2]);
  wire w105;
  nand g8815__5107 (n_239, w105, n_184);
  or g105 (w105, n_178, n_183);
  nand g8808__6260 (n_192, unfilteredLFSR0[9], n_179);
  not g8822 (n_177, n_176);
  wire w106;
  nor g8824__4319 (n_185, w106, n_175);
  and g106 (w106, n_159, n_174);
  wire w107;
  nand g8817__8428 (n_241, w107, n_184);
  or g107 (w107, n_182, n_46);
  wire w108;
  nor g8830__5526 (n_329, w108, n_175);
  and g108 (w108, n_174, n_157);
  not g8810 (n_173, n_172);
  wire w109, w110, w111, w112;
  nand g8807__6783 (n_171, w110, w112);
  nand g112 (w112, w111, unfilteredLFSR5[6]);
  not g111 (w111, unfilteredLFSR5[9]);
  nand g110 (w110, w109, unfilteredLFSR5[9]);
  not g109 (w109, unfilteredLFSR5[6]);
  wire w113;
  nand g8825__3680 (n_318, w113, unfilteredLFSR2[8]);
  or g113 (w113, n_165, n_164);
  wire w114;
  nor g8800__1617 (n_204, w114, n_170);
  and g114 (w114, n_160, unfilteredLFSR5[9]);
  nand g8820__2802 (result[6], n_170, n_320);
  not g8833 (n_169, n_168);
  wire w115;
  nand g8828__1705 (n_299, w115, n_167);
  or g115 (w115, n_166, n_163);
  wire w116;
  nand g8829__5122 (n_298, w116, n_167);
  or g116 (w116, n_165, n_166);
  wire w117;
  nand g8827__8246 (n_176, w117, unfilteredLFSR2[8]);
  or g117 (w117, n_163, n_164);
  not g8845 (n_252, n_155);
  DFF_X2 \LFSR2_r_LFSR_reg[1] (.CK (clk), .D (n_151), .Q
       (UNCONNECTED2), .QN (unfilteredLFSR2[0]));
  nor g8812__7098 (n_162, n_45, n_196);
  nand g8831__6131 (n_161, unfilteredLFSR5[9], n_160);
  nand g8818__1881 (n_172, unfilteredLFSR5[9], n_138);
  DFF_X2 \LFSR6_r_LFSR_reg[1] (.CK (clk), .D (n_150), .Q
       (UNCONNECTED3), .QN (unfilteredLFSR6[0]));
  wire w118;
  nor g8826__5115 (n_206, w118, n_158);
  and g118 (w118, n_156, n_159);
  wire w119;
  nor g8832__7482 (n_343, w119, n_158);
  and g119 (w119, n_156, n_157);
  or g8819__4733 (n_179, unfilteredLFSR0[4], n_196);
  wire w120;
  nor g8852__6161 (n_155, w120, n_153);
  and g120 (w120, n_159, n_152);
  wire w121, w122, w123, w124;
  nand g8846__9315 (n_154, w122, w124);
  nand g124 (w124, w123, n_136);
  not g123 (w123, n_137);
  nand g122 (w122, w121, n_137);
  not g121 (w121, n_136);
  wire w125;
  nor g8849__9945 (n_249, w125, n_153);
  and g125 (w125, n_152, n_157);
  wire w126;
  nor g8838__2883 (n_168, w126, n_153);
  and g126 (w126, n_38, n_152);
  not g8835 (n_187, unfilteredLFSR0[9]);
  not g8834 (n_175, n_167);
  nor g8842__2346 (n_184, n_152, n_153);
  wire w127;
  nor g8811__1666 (n_151, n_127, n_121, w127);
  and g127 (w127, unfilteredLFSR2[4], unfilteredLFSR2[8]);
  not g8836 (n_320, n_223);
  wire w128;
  nand g8851__7410 (n_242, w128, n_143);
  or g128 (w128, n_132, n_163);
  DFF_X2 \LFSR0_r_LFSR_reg[10] (.CK (clk), .D (n_142), .Q
       (unfilteredLFSR0[9]), .QN (UNCONNECTED4));
  nor g8840__6417 (n_167, n_158, n_156);
  nand g8813__5477 (n_150, n_193, n_131);
  wire w129;
  nand g8853__2398 (n_273, n_134, n_144, w129);
  or g129 (w129, unfilteredLFSR3[1], n_126);
  nand g8839__5107 (n_170, n_190, n_149);
  nor g8844__6260 (n_223, n_190, n_149);
  DFF_X2 \LFSR5_r_LFSR_reg[10] (.CK (clk), .D (n_130), .Q
       (unfilteredLFSR5[9]), .QN (UNCONNECTED5));
  not g8863 (n_148, n_147);
  not g8880 (n_146, n_145);
  and g8859__4319 (n_277, n_144, n_129);
  not g8864 (n_164, n_156);
  or g8854__8428 (n_196, unfilteredLFSR0[7], unfilteredLFSR0[5],
       unfilteredLFSR0[8], unfilteredLFSR0[6]);
  not g8855 (n_153, n_143);
  and g8857__5526 (n_142, n_193, unfilteredLFSR0[8]);
  nand g8860__6783 (n_141, n_139, n_140);
  nor g8848__3680 (n_138, unfilteredLFSR5[8], n_117,
       unfilteredLFSR5[6], n_80);
  nor g8862__1617 (n_143, n_158, n_174);
  wire w130;
  nand g8850__2802 (n_215, n_139, n_135, w130);
  or g130 (w130, n_137, n_119);
  wire w131, w132, w133, w134;
  nand g8887__1705 (n_136, w132, w134);
  nand g134 (w134, w133, n_139);
  not g133 (w133, n_74);
  nand g132 (w132, w131, n_74);
  not g131 (w131, n_139);
  wire w135, w136;
  nand g8869__5122 (n_147, w135, w136, n_144);
  or g136 (w136, unfilteredLFSR3[4], n_133);
  or g135 (w135, n_125, n_123);
  wire w137;
  nand g8870__8246 (n_247, n_139, n_135, w137);
  or g137 (w137, n_137, n_128);
  nand g8886__7098 (n_145, n_133, n_134, n_144);
  nor g8871__6131 (n_156, unfilteredLFSR2[5], n_132);
  wire w138, w139, w140, w141;
  nand g8847__1881 (n_131, w139, w141);
  nand g141 (w141, w140, unfilteredLFSR6[8]);
  not g140 (w140, unfilteredLFSR6[4]);
  nand g139 (w139, w138, unfilteredLFSR6[4]);
  not g138 (w138, unfilteredLFSR6[8]);
  nand g8856__5115 (n_130, n_193, unfilteredLFSR5[8]);
  or g8858__7482 (n_149, unfilteredLFSR6[7], unfilteredLFSR6[6],
       unfilteredLFSR6[8], n_78);
  or g8883__4733 (n_129, unfilteredLFSR3[4], n_107, n_128);
  nor g8865__6161 (n_127, unfilteredLFSR2[4], unfilteredLFSR2[8]);
  wire w142;
  nand g8885__9315 (n_216, w142, n_139);
  or g142 (w142, n_53, n_135);
  wire w143;
  nand g8866__9945 (n_160, w143, unfilteredLFSR5[8]);
  or g143 (w143, unfilteredLFSR5[6], n_106);
  not g8881 (n_166, n_174);
  DFF_X2 \LFSR0_r_LFSR_reg[9] (.CK (clk), .D (n_120), .Q
       (unfilteredLFSR0[8]), .QN (UNCONNECTED6));
  not g8882 (n_132, n_152);
  not g8872 (n_158, unfilteredLFSR2[8]);
  nand g8892__2883 (n_126, unfilteredLFSR3[0], n_124);
  DFF_X2 \LFSR7_r_LFSR_reg[1] (.CK (clk), .D (n_122), .Q
       (UNCONNECTED7), .QN (LFSR7_r_LFSR[1]));
  or g8884__2346 (n_140, n_125, unfilteredLFSR3[3], n_135);
  wire w144;
  nor g8902__1666 (n_144, w144, unfilteredLFSR3[7]);
  and g144 (w144, unfilteredLFSR3[5], n_113);
  DFF_X2 \LFSR5_r_LFSR_reg[9] (.CK (clk), .D (n_118), .Q
       (UNCONNECTED8), .QN (unfilteredLFSR5[8]));
  nor g8889__7410 (n_174, unfilteredLFSR2[5], n_182);
  DFF_X2 \LFSR2_r_LFSR_reg[9] (.CK (clk), .D (n_116), .Q
       (unfilteredLFSR2[8]), .QN (UNCONNECTED9));
  not g8916 (n_128, n_124);
  nor g8890__6417 (n_152, unfilteredLFSR2[4], n_182);
  not g8906 (n_139, unfilteredLFSR3[7]);
  or g8919__5477 (n_123, unfilteredLFSR3[1], n_134);
  DFF_X2 \LFSR1_r_LFSR_reg[1] (.CK (clk), .D (n_105), .Q
       (unfilteredLFSR1[0]), .QN (UNCONNECTED10));
  nor g8922__2398 (n_124, n_125, n_133);
  DFF_X2 \LFSR4_r_LFSR_reg[1] (.CK (clk), .D (n_110), .Q
       (UNCONNECTED11), .QN (unfilteredLFSR4[0]));
  or g8923__5107 (n_135, n_137, n_134);
  wire w145, w146;
  nor g8867__6260 (n_122, w145, n_121, w146);
  and g146 (w146, result[7], n_91);
  and g145 (w145, n_190, n_92);
  or g8894__4319 (n_120, n_112, unfilteredLFSR0[7]);
  and g8891__8428 (n_119, n_133, n_108);
  DFF_X2 \LFSR3_r_LFSR_reg[8] (.CK (clk), .D (n_114), .Q
       (UNCONNECTED12), .QN (unfilteredLFSR3[7]));
  DFF_X2 \LFSR6_r_LFSR_reg[9] (.CK (clk), .D (n_111), .Q
       (UNCONNECTED13), .QN (unfilteredLFSR6[8]));
  nand g8888__5526 (n_183, n_42, n_115);
  nand g8896__6783 (n_118, n_193, n_117);
  nor g8898__3680 (n_116, n_121, n_101);
  not g8897 (n_182, n_115);
  nor g8930__1617 (n_114, n_112, n_113);
  nor g8893__2802 (n_111, n_112, unfilteredLFSR6[7]);
  wire w147;
  nand g8873__1705 (n_110, w147, n_1);
  or g147 (w147, n_94, n_109);
  wire w148;
  nand g8868__5122 (n_213, n_109, n_90, w148);
  or g148 (w148, unfilteredLFSR4[4], n_26);
  nand g8933__8246 (n_134, n_113, n_72);
  nand g8941__7098 (n_133, n_113, n_73);
  or g8917__6131 (n_108, unfilteredLFSR3[6], n_125, n_107);
  wire w149;
  nand g8899__1881 (n_106, w149, unfilteredLFSR5[7]);
  or g149 (w149, unfilteredLFSR5[5], n_65);
  nand g8895__5115 (n_105, n_193, n_96);
  nor g8903__7482 (n_115, unfilteredLFSR2[7], unfilteredLFSR2[6]);
  DFF_X2 \LFSR0_r_LFSR_reg[8] (.CK (clk), .D (n_99), .Q
       (unfilteredLFSR0[7]), .QN (UNCONNECTED14));
  and g8908__4733 (n_325, n_349, n_100);
  wire w150;
  nor g8900__6161 (n_327, w150, unfilteredLFSR1[6]);
  and g150 (w150, n_103, n_104);
  nor g8921__9315 (n_316, unfilteredLFSR1[6], n_103);
  not g8905 (n_117, unfilteredLFSR5[7]);
  wire w151;
  nor g8924__9945 (n_295, w151, n_102);
  and g151 (w151, n_232, n_104);
  not g8904 (n_101, unfilteredLFSR2[7]);
  and g8874__2883 (n_200, n_109, n_69);
  wire w152;
  nand g8901__2346 (n_323, w152, n_95);
  or g152 (w152, unfilteredLFSR1[2], n_100);
  not g8907 (n_190, result[7]);
  or g8926__1666 (n_99, n_112, unfilteredLFSR0[6]);
  not g8925 (n_98, n_97);
  not g8949 (n_113, unfilteredLFSR3[6]);
  DFF_X2 \LFSR7_r_LFSR_reg[8] (.CK (clk), .D (n_85), .Q
       (UNCONNECTED15), .QN (result[7]));
  wire w153, w154, w155, w156;
  nand g8918__7410 (n_96, w154, w156);
  nand g156 (w156, w155, unfilteredLFSR1[5]);
  not g155 (w155, n_95);
  nand g154 (w154, w153, n_95);
  not g153 (w153, unfilteredLFSR1[5]);
  DFF_X2 \LFSR2_r_LFSR_reg[8] (.CK (clk), .D (n_86), .Q
       (unfilteredLFSR2[7]), .QN (UNCONNECTED16));
  DFF_X2 \LFSR6_r_LFSR_reg[8] (.CK (clk), .D (n_87), .Q
       (UNCONNECTED17), .QN (unfilteredLFSR6[7]));
  DFF_X2 \LFSR5_r_LFSR_reg[8] (.CK (clk), .D (n_88), .Q
       (unfilteredLFSR5[7]), .QN (UNCONNECTED18));
  not g8934 (n_349, n_102);
  nor g8935__6417 (n_94, unfilteredLFSR4[6], unfilteredLFSR4[5]);
  nor g8936__5477 (n_103, unfilteredLFSR1[2], n_93);
  wire w157;
  nand g8932__2398 (n_97, w157, unfilteredLFSR4[6]);
  or g157 (w157, unfilteredLFSR4[5], n_64);
  nand g8937__5107 (n_267, n_95, n_89);
  not g8915 (n_92, n_91);
  DFF_X2 \LFSR3_r_LFSR_reg[7] (.CK (clk), .D (n_84), .Q
       (unfilteredLFSR3[6]), .QN (UNCONNECTED19));
  wire w158;
  nand g8939__6260 (n_189, w158, unfilteredLFSR4[6]);
  or g158 (w158, unfilteredLFSR4[5], n_90);
  and g8940__4319 (n_109, unfilteredLFSR4[6], unfilteredLFSR4[5]);
  wire w159;
  nand g8942__8428 (n_102, w159, n_95);
  or g159 (w159, unfilteredLFSR1[2], n_89);
  nor g8927__5526 (n_88, n_0, unfilteredLFSR5[6]);
  nor g8928__6783 (n_87, n_112, unfilteredLFSR6[6]);
  wire w160, w161, w162, w163;
  nand g8920__3680 (n_91, w161, w163);
  nand g163 (w163, w162, n_79);
  not g162 (w162, LFSR7_r_LFSR[4]);
  nand g161 (w161, w160, LFSR7_r_LFSR[4]);
  not g160 (w160, n_79);
  or g8931__1617 (n_86, n_112, unfilteredLFSR2[6]);
  nor g8929__2802 (n_85, n_112, LFSR7_r_LFSR[7]);
  wire w164;
  nor g8938__1705 (n_100, w164, n_232);
  and g164 (w164, n_82, n_104);
  DFF_X2 \LFSR0_r_LFSR_reg[7] (.CK (clk), .D (n_83), .Q
       (unfilteredLFSR0[6]), .QN (UNCONNECTED20));
  not g8950 (n_93, n_232);
  not g8943 (n_95, unfilteredLFSR1[6]);
  nor g8964__5122 (n_84, n_121, unfilteredLFSR3[5]);
  DFF_X2 \LFSR4_r_LFSR_reg[7] (.CK (clk), .D (n_81), .Q
       (unfilteredLFSR4[6]), .QN (UNCONNECTED21));
  DFF_X2 \LFSR7_r_LFSR_reg[7] (.CK (clk), .D (n_76), .Q
       (UNCONNECTED22), .QN (LFSR7_r_LFSR[7]));
  DFF_X2 \LFSR6_r_LFSR_reg[7] (.CK (clk), .D (n_77), .Q
       (UNCONNECTED23), .QN (unfilteredLFSR6[6]));
  DFF_X2 \LFSR2_r_LFSR_reg[7] (.CK (clk), .D (n_70), .Q
       (unfilteredLFSR2[6]), .QN (UNCONNECTED24));
  DFF_X2 \LFSR5_r_LFSR_reg[7] (.CK (clk), .D (n_75), .Q
       (UNCONNECTED25), .QN (unfilteredLFSR5[6]));
  and g8965__8246 (n_83, n_193, unfilteredLFSR0[5]);
  DFF_X2 \LFSR1_r_LFSR_reg[7] (.CK (clk), .D (n_71), .Q
       (UNCONNECTED26), .QN (unfilteredLFSR1[6]));
  not g8968 (n_137, unfilteredLFSR3[5]);
  nor g8955__7098 (n_232, unfilteredLFSR1[1], n_89);
  not g8961 (n_82, n_89);
  and g8957__6131 (n_81, n_193, unfilteredLFSR4[5]);
  nor g8966__1881 (n_80, unfilteredLFSR5[4], unfilteredLFSR5[3],
       unfilteredLFSR5[5], n_33);
  wire w165, w166, w167, w168;
  nand g8951__5115 (n_79, w166, w168);
  nand g168 (w168, w167, LFSR7_r_LFSR[6]);
  not g167 (w167, LFSR7_r_LFSR[5]);
  nand g166 (w166, w165, LFSR7_r_LFSR[5]);
  not g165 (w165, LFSR7_r_LFSR[6]);
  DFF_X2 \LFSR3_r_LFSR_reg[6] (.CK (clk), .D (n_68), .Q
       (UNCONNECTED27), .QN (unfilteredLFSR3[5]));
  or g8958__7482 (n_78, unfilteredLFSR6[5], n_58);
  nand g8956__4733 (n_77, n_193, unfilteredLFSR6[5]);
  nand g8960__6161 (n_76, n_193, LFSR7_r_LFSR[6]);
  or g8959__9315 (n_75, n_112, unfilteredLFSR5[5]);
  wire w169, w170;
  and g8975__9945 (n_74, w169, w170);
  nand g170 (w170, n_72, unfilteredLFSR3[3]);
  nand g169 (w169, n_73, unfilteredLFSR3[4]);
  nand g8962__2883 (n_71, n_193, unfilteredLFSR1[5]);
  or g8963__2346 (n_70, n_112, unfilteredLFSR2[5]);
  DFF_X2 \LFSR0_r_LFSR_reg[6] (.CK (clk), .D (n_67), .Q
       (unfilteredLFSR0[5]), .QN (UNCONNECTED28));
  nand g8967__1666 (n_89, unfilteredLFSR1[4], unfilteredLFSR1[3],
       unfilteredLFSR1[5]);
  DFF_X2 \LFSR4_r_LFSR_reg[6] (.CK (clk), .D (n_66), .Q
       (unfilteredLFSR4[5]), .QN (UNCONNECTED29));
  or g8974__7410 (n_69, n_48, n_47, n_90);
  nand g8986__6417 (n_68, n_193, n_72);
  and g8985__5477 (n_67, n_193, unfilteredLFSR0[4]);
  DFF_X2 \LFSR7_r_LFSR_reg[6] (.CK (clk), .D (n_60), .Q
       (UNCONNECTED30), .QN (LFSR7_r_LFSR[6]));
  DFF_X2 \LFSR5_r_LFSR_reg[6] (.CK (clk), .D (n_59), .Q
       (unfilteredLFSR5[5]), .QN (UNCONNECTED31));
  DFF_X2 \LFSR6_r_LFSR_reg[6] (.CK (clk), .D (n_62), .Q
       (UNCONNECTED32), .QN (unfilteredLFSR6[5]));
  DFF_X2 \LFSR1_r_LFSR_reg[6] (.CK (clk), .D (n_63), .Q
       (UNCONNECTED33), .QN (unfilteredLFSR1[5]));
  DFF_X2 \LFSR2_r_LFSR_reg[6] (.CK (clk), .D (n_57), .Q
       (unfilteredLFSR2[5]), .QN (UNCONNECTED34));
  or g8981__2398 (n_66, n_61, unfilteredLFSR4[4]);
  and g8988__5107 (n_65, unfilteredLFSR5[4], unfilteredLFSR5[2],
       unfilteredLFSR5[3]);
  and g8979__6260 (n_64, unfilteredLFSR4[4], n_54);
  or g8990__4319 (n_90, unfilteredLFSR4[4], unfilteredLFSR4[3]);
  not g8995 (n_72, unfilteredLFSR3[4]);
  nand g8982__8428 (n_63, n_193, unfilteredLFSR1[4]);
  or g8984__5526 (n_62, n_61, unfilteredLFSR6[4]);
  and g8980__6783 (n_60, n_193, LFSR7_r_LFSR[5]);
  and g8983__3680 (n_59, n_193, unfilteredLFSR5[4]);
  wire w171;
  nor g8989__1617 (n_58, w171, unfilteredLFSR6[4]);
  and g171 (w171, n_25, unfilteredLFSR6[3]);
  and g8987__2802 (n_57, n_193, unfilteredLFSR2[4]);
  DFF_X2 \LFSR0_r_LFSR_reg[5] (.CK (clk), .D (n_52), .Q
       (unfilteredLFSR0[4]), .QN (UNCONNECTED35));
  DFF_X2 \LFSR3_r_LFSR_reg[5] (.CK (clk), .D (n_55), .Q
       (unfilteredLFSR3[4]), .QN (UNCONNECTED36));
  nor g9010__1705 (n_56, n_34, unfilteredLFSR0[1], unfilteredLFSR0[0],
       n_195);
  DFF_X2 \LFSR4_r_LFSR_reg[5] (.CK (clk), .D (n_50), .Q
       (unfilteredLFSR4[4]), .QN (UNCONNECTED37));
  nor g9006__5122 (n_55, n_51, n_73);
  DFF_X2 \LFSR1_r_LFSR_reg[5] (.CK (clk), .D (n_40), .Q
       (UNCONNECTED38), .QN (unfilteredLFSR1[4]));
  DFF_X2 \LFSR7_r_LFSR_reg[5] (.CK (clk), .D (n_41), .Q
       (LFSR7_r_LFSR[5]), .QN (UNCONNECTED39));
  DFF_X2 \LFSR2_r_LFSR_reg[5] (.CK (clk), .D (n_43), .Q
       (unfilteredLFSR2[4]), .QN (UNCONNECTED40));
  not g9009 (n_54, n_49);
  nor g9013__8246 (n_53, unfilteredLFSR3[2], n_73);
  nor g9008__7098 (n_52, n_51, n_195);
  DFF_X2 \LFSR5_r_LFSR_reg[5] (.CK (clk), .D (n_44), .Q
       (unfilteredLFSR5[4]), .QN (UNCONNECTED41));
  DFF_X2 \LFSR6_r_LFSR_reg[5] (.CK (clk), .D (n_39), .Q
       (unfilteredLFSR6[4]), .QN (UNCONNECTED42));
  and g9001__6131 (n_50, n_193, unfilteredLFSR4[3]);
  wire w172;
  nor g9012__1881 (n_49, w172, unfilteredLFSR4[3]);
  and g172 (w172, n_47, n_48);
  nand g8996__5115 (n_46, unfilteredLFSR2[0], n_159);
  and g9014__7482 (n_191, unfilteredLFSR0[3], n_45);
  and g9003__4733 (n_44, n_193, unfilteredLFSR5[3]);
  nand g9002__6161 (n_43, n_193, n_42);
  or g9011__9315 (n_41, n_61, LFSR7_r_LFSR[4]);
  nor g9015__9945 (n_165, n_42, n_28);
  nor g9004__2883 (n_40, n_61, unfilteredLFSR1[3]);
  and g9007__2346 (n_39, n_193, unfilteredLFSR6[3]);
  nor g9016__1666 (n_163, n_42, n_36);
  not g9019 (n_73, unfilteredLFSR3[3]);
  not g9024 (n_195, unfilteredLFSR0[3]);
  nand g9005__7410 (n_38, unfilteredLFSR2[3], n_178);
  DFF_X2 \LFSR0_r_LFSR_reg[4] (.CK (clk), .D (n_31), .Q
       (unfilteredLFSR0[3]), .QN (UNCONNECTED43));
  DFF_X2 \LFSR4_r_LFSR_reg[4] (.CK (clk), .D (n_35), .Q
       (unfilteredLFSR4[3]), .QN (UNCONNECTED44));
  DFF_X2 \LFSR3_r_LFSR_reg[4] (.CK (clk), .D (n_32), .Q
       (unfilteredLFSR3[3]), .QN (UNCONNECTED45));
  nor g9017__6417 (n_157, unfilteredLFSR2[3], n_27);
  nor g9018__5477 (n_159, unfilteredLFSR2[3], n_22);
  nand g9026__2398 (n_37, unfilteredLFSR2[0], n_36);
  DFF_X2 \LFSR1_r_LFSR_reg[4] (.CK (clk), .D (n_24), .Q
       (UNCONNECTED46), .QN (unfilteredLFSR1[3]));
  DFF_X2 \LFSR5_r_LFSR_reg[4] (.CK (clk), .D (n_23), .Q
       (unfilteredLFSR5[3]), .QN (UNCONNECTED47));
  DFF_X2 \LFSR6_r_LFSR_reg[4] (.CK (clk), .D (n_30), .Q
       (unfilteredLFSR6[3]), .QN (UNCONNECTED48));
  DFF_X2 \LFSR7_r_LFSR_reg[4] (.CK (clk), .D (n_29), .Q
       (LFSR7_r_LFSR[4]), .QN (UNCONNECTED49));
  not g9025 (n_42, unfilteredLFSR2[3]);
  or g9037__5107 (n_35, n_112, n_48);
  nand g9044__6260 (n_45, n_34, unfilteredLFSR0[1]);
  DFF_X2 \LFSR2_r_LFSR_reg[4] (.CK (clk), .D (n_21), .Q
       (unfilteredLFSR2[3]), .QN (UNCONNECTED50));
  wire w173;
  nor g9040__4319 (n_33, w173, n_20);
  and g173 (w173, unfilteredLFSR5[0], unfilteredLFSR5[1]);
  nand g9033__8428 (n_32, n_193, unfilteredLFSR3[2]);
  nor g9031__5526 (n_31, n_121, n_34);
  nor g9036__6783 (n_30, n_112, unfilteredLFSR6[2]);
  nor g9043__3680 (n_29, n_121, LFSR7_r_LFSR[3]);
  not g9038 (n_28, n_27);
  not g9055 (n_125, unfilteredLFSR3[2]);
  wire w174;
  nor g9042__1617 (n_26, w174, unfilteredLFSR4[2]);
  and g174 (w174, unfilteredLFSR4[0], unfilteredLFSR4[1]);
  nand g9041__2802 (n_25, unfilteredLFSR6[1], unfilteredLFSR6[0],
       unfilteredLFSR6[2]);
  and g9034__1705 (n_24, n_193, unfilteredLFSR1[2]);
  or g9032__5122 (n_23, n_112, unfilteredLFSR5[2]);
  not g9039 (n_36, n_22);
  nor g9045__8246 (n_27, unfilteredLFSR2[1], unfilteredLFSR2[2]);
  wire w175;
  nor g9047__7098 (n_178, w175, unfilteredLFSR2[2]);
  and g175 (w175, unfilteredLFSR2[0], unfilteredLFSR2[1]);
  not g9048 (n_34, unfilteredLFSR0[2]);
  not g9054 (n_48, unfilteredLFSR4[2]);
  nor g9035__6131 (n_21, n_112, unfilteredLFSR2[2]);
  not g9053 (n_20, unfilteredLFSR5[2]);
  nand g9046__1881 (n_22, unfilteredLFSR2[2], unfilteredLFSR2[1]);
  DFF_X2 \LFSR3_r_LFSR_reg[3] (.CK (clk), .D (n_19), .Q
       (UNCONNECTED51), .QN (unfilteredLFSR3[2]));
  DFF_X2 \LFSR7_r_LFSR_reg[3] (.CK (clk), .D (n_14), .Q
       (UNCONNECTED52), .QN (LFSR7_r_LFSR[3]));
  DFF_X2 \LFSR6_r_LFSR_reg[3] (.CK (clk), .D (n_15), .Q
       (UNCONNECTED53), .QN (unfilteredLFSR6[2]));
  DFF_X2 \LFSR0_r_LFSR_reg[3] (.CK (clk), .D (n_12), .Q
       (unfilteredLFSR0[2]), .QN (UNCONNECTED54));
  DFF_X2 \LFSR4_r_LFSR_reg[3] (.CK (clk), .D (n_16), .Q
       (UNCONNECTED55), .QN (unfilteredLFSR4[2]));
  DFF_X2 \LFSR5_r_LFSR_reg[3] (.CK (clk), .D (n_13), .Q
       (unfilteredLFSR5[2]), .QN (UNCONNECTED56));
  DFF_X2 \LFSR1_r_LFSR_reg[3] (.CK (clk), .D (n_11), .Q
       (unfilteredLFSR1[2]), .QN (UNCONNECTED57));
  DFF_X2 \LFSR2_r_LFSR_reg[3] (.CK (clk), .D (n_10), .Q
       (UNCONNECTED58), .QN (unfilteredLFSR2[2]));
  nor g9068__5115 (n_19, n_61, n_18);
  nor g9063__7482 (n_107, unfilteredLFSR3[0], n_18);
  nand g9060__4733 (n_17, unfilteredLFSR0[1], unfilteredLFSR0[0]);
  nor g9061__6161 (n_16, n_61, unfilteredLFSR4[1]);
  nand g9067__9315 (n_15, n_193, unfilteredLFSR6[1]);
  nor g9064__9945 (n_47, unfilteredLFSR4[0], unfilteredLFSR4[1]);
  nand g9065__2883 (n_14, n_193, LFSR7_r_LFSR[2]);
  nor g9069__2346 (n_13, n_61, unfilteredLFSR5[1]);
  nand g9062__1666 (n_12, n_193, unfilteredLFSR0[1]);
  or g9066__7410 (n_11, n_51, unfilteredLFSR1[1]);
  nand g9070__6417 (n_10, n_193, unfilteredLFSR2[1]);
  not g9071 (n_18, unfilteredLFSR3[1]);
  DFF_X2 \LFSR7_r_LFSR_reg[2] (.CK (clk), .D (n_5), .Q (UNCONNECTED59),
       .QN (LFSR7_r_LFSR[2]));
  DFF_X2 \LFSR5_r_LFSR_reg[2] (.CK (clk), .D (n_4), .Q (UNCONNECTED60),
       .QN (unfilteredLFSR5[1]));
  DFF_X2 \LFSR4_r_LFSR_reg[2] (.CK (clk), .D (n_7), .Q (UNCONNECTED61),
       .QN (unfilteredLFSR4[1]));
  DFF_X2 \LFSR1_r_LFSR_reg[2] (.CK (clk), .D (n_6), .Q
       (unfilteredLFSR1[1]), .QN (UNCONNECTED62));
  DFF_X2 \LFSR6_r_LFSR_reg[2] (.CK (clk), .D (n_3), .Q (UNCONNECTED63),
       .QN (unfilteredLFSR6[1]));
  DFF_X2 \LFSR3_r_LFSR_reg[2] (.CK (clk), .D (n_9), .Q
       (unfilteredLFSR3[1]), .QN (UNCONNECTED64));
  DFF_X2 \LFSR0_r_LFSR_reg[2] (.CK (clk), .D (n_8), .Q (UNCONNECTED65),
       .QN (unfilteredLFSR0[1]));
  DFF_X2 \LFSR2_r_LFSR_reg[2] (.CK (clk), .D (n_2), .Q (UNCONNECTED66),
       .QN (unfilteredLFSR2[1]));
  nor g9081__5477 (n_9, n_121, unfilteredLFSR3[0]);
  nor g9083__2398 (n_8, n_51, unfilteredLFSR0[0]);
  nor g9086__5107 (n_7, n_112, unfilteredLFSR4[0]);
  nor g9085__6260 (n_6, n_121, n_104);
  nor g9087__4319 (n_5, n_112, LFSR7_r_LFSR[1]);
  nor g9084__8428 (n_4, n_61, unfilteredLFSR5[0]);
  nor g9080__5526 (n_3, n_112, unfilteredLFSR6[0]);
  nand g9082__6783 (n_2, n_193, unfilteredLFSR2[0]);
  not g9092 (n_51, n_1);
  not g9090 (n_121, n_1);
  not g9091 (n_0, n_1);
  not g9093 (n_61, n_1);
  not g9094 (n_112, n_1);
  not g9089 (n_193, LD_seed);
  not g9088 (n_104, unfilteredLFSR1[0]);
  not g9095 (n_1, LD_seed);
endmodule


module DFF_X2(CK, D, QN, Q);
  input CK, D;
  output QN, Q;
  wire CK, D;
  wire QN, Q;
  wire next_state;
  reg  qi;
  assign #1 QN = qi, Q = !qi;
  not g176 (next_state, D);
  always 
    @(posedge CK) 
      qi <= next_state;
  initial 
    qi <= 1'b0;
endmodule
